### ISSUE TITLE
Krisp_fasta issue of no space left of device in CQLS

### ISSUE THREAD

**Issue by buchanri** [grunwaldlab/krisp#22]
Hi! I'm running `krisp_fasta` in the CQLS  using the following command:

`~/mambaforge/bin/krisp_fasta /nfs7/BPP/Chang_Lab/buchanri/agro_crispr_dx/data/fna_assemblies/*BV1* --outgroup /nfs7/BPP/Chang_Lab/buchanri/agro_crispr_dx/data/fna_assemblies/*BV2* /nfs7/BPP/Chang_Lab/buchanri/agro_crispr_dx/data/fna_assemblies/*BV3* --conserved-left 8 --diagnostic 1 --conserved-right 19 --dot-alignment --cores 32 --workdir /nfs7/BPP/Chang_Lab/buchanri/agro_crispr_dx/results/tmp/ --out_csv /nfs7/BPP/Chang_Lab/buchanri/agro_crispr_dx/results/BV1_krisp_fasta_out/BV1_nt9_align.csv`

Starts with using krisp_fasta where I have it located. BV1 being the ingroup and BV2 and BV3 are the outgroups. The options that we want are the dot alignment, core utilization, path to a working directory for tmp files, and the path to where we want the .csv to be put.
But I keep getting the error of:

`sort: cannot create temporary file in '/tmp': No space left on device `
`sort: close failed: /tmp/sort20HP90: No space left on device`

I've tried running the command both with and without a working directory but keep getting the same error. Do you have any suggestions on how to bypass this issue?

**Comment by zachary-foster** [comment]
This is due to how the cluster is set up and how much temporary files are used by `krisp_fasta`. You should be able to use the `--workdir` option to make the temporary files be saved somewhere besides the default `/tmp` directory that has limited space.

**Comment by zachary-foster** [comment]
Feel free to reopen if this does not work.
